// SETTERS

// GETTERS

// ACTIONS
const REGISTER_WEB_3 = 'REGISTER_WEB_3'
const POLL_WEB_3 = 'POLL_WEB_3'
const SUBMIT_REVIEW = 'SUBMIT_REVIEW'
const GET_REVIEWS = 'GET_REVIEWS'
const UPVOTE_REVIEW = 'UPVOTE_REVIEW'

// MUTATIONS
const REGISTER_WEB_3_INSTANCE = 'REGISTER_WEB_3_INSTANCE'
const POLL_WEB_3_INSTANCE = 'POLL_WEB_3_INSTANCE'
const REGISTER_ETH_LEND_CONTRACT_INSTANCE = 'REGISTER_ETH_LEND_CONTRACT_INSTANCE'
const SET_REVIEWS_INDEXES = 'SET_REVIEWS_INDEXES'

export default {
  REGISTER_WEB_3,
  POLL_WEB_3,
  SUBMIT_REVIEW,
  GET_REVIEWS,
  UPVOTE_REVIEW,
  REGISTER_WEB_3_INSTANCE,
  POLL_WEB_3_INSTANCE,
  REGISTER_ETH_LEND_CONTRACT_INSTANCE,
  SET_REVIEWS_INDEXES
}
